### ISSUE TITLE
Unable to use in node when not transpiling node_modules

### ISSUE THREAD

**Issue by RyanHirsch** [MatthiasKunnen/rxjs-take-while-inclusive#1]
I am unable to use this module because it is published as a es6 module and I do not transpile anything in `node_modules`. If this were published as `umd` rather than `es6` it would be consumable.

I can submit a PR if you want to accept.

**Comment by MatthiasKunnen** [comment]
The published package is es5 though, doesn't that work? What's your setup?

**Comment by RyanHirsch** [comment]
If I look at the published package it has `import` statements. As seen here - https://unpkg.com/rxjs-take-while-inclusive@2.0.1/index.js 

Example repository - https://github.com/RyanHirsch/inclusive-test
The error I get is

```
import { Subscriber, } from 'rxjs';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by MatthiasKunnen** [comment]
I see, I'll have a look later today. Out of curiosity, which version of Node are you using?

**Comment by RyanHirsch** [comment]
Using Node 10.4 and 10.3

**Comment by MatthiasKunnen** [comment]
Can you see whether it works using v2.1.0? You'll need to use `const { takeWhileInclusive } = require('rxjs-take-while-inclusive');` due to the way the exports are set up.

**Comment by RyanHirsch** [comment]
I upgraded the version in my sample repo and it works! Thank you so much.

```js
const { interval } = require('rxjs');
const { takeWhileInclusive } = require('rxjs-take-while-inclusive');

interval(100)
  .pipe(takeWhileInclusive(x => x < 10))
  .subscribe(console.log);
```

**Comment by MatthiasKunnen** [comment]
You're welcome, happy to help!
